# Master list of the 200 MCCPS SEO pages: (category, slug, working title, angle)
IND = [  # /industries/<slug>/ — 50: payment processing for an industry
("restaurants","Restaurant Payment Processing","tableside/tap, tips, high volume small tickets, POS integration"),
("retail-stores","Retail Payment Processing","countertop EMV, inventory-linked POS, returns, holiday peaks"),
("ecommerce","E-commerce Payment Processing","gateway, cart plugins, card-not-present fraud, chargebacks"),
("bars-and-nightclubs","Bar & Nightclub Payment Processing","pre-auth tabs, tips, speed at rush, chargebacks"),
("coffee-shops","Coffee Shop Payment Processing","micro-transactions, tap, loyalty, per-transaction fee impact"),
("food-trucks","Food Truck Payment Processing","mobile readers, offline mode, event volume"),
("quick-service-restaurants","Quick-Service Restaurant Payment Processing","speed, kiosks, online ordering, drive-thru"),
("salons-and-spas","Salon & Spa Payment Processing","appointments, deposits/no-show fees, tips, retail products"),
("barbershops","Barbershop Payment Processing","walk-ins, tips, booth renters"),
("gyms-and-fitness","Gym & Fitness Studio Payment Processing","recurring memberships, failed payments, account updater"),
("medical-practices","Medical Practice Payment Processing","patient copays, HSA/FSA cards, payment plans, PCI and privacy"),
("dental-practices","Dental Practice Payment Processing","treatment plans, financing, card-on-file"),
("veterinary-clinics","Veterinary Clinic Payment Processing","large unexpected bills, card-on-file, deposits"),
("chiropractors","Chiropractic Payment Processing","packages, recurring care plans"),
("auto-repair-shops","Auto Repair Shop Payment Processing","large tickets, key-entry, Level 2 for fleets"),
("car-dealerships","Car Dealership Payment Processing","deposits, high ticket, card limits, ACH"),
("hvac-and-plumbing","HVAC & Plumbing Payment Processing","field payments, invoices, mobile"),
("contractors","Contractor Payment Processing","deposits, progress billing, B2B Level 2/3, ACH"),
("landscaping","Landscaping Payment Processing","recurring service plans, invoicing, seasonal"),
("cleaning-services","Cleaning Service Payment Processing","recurring billing, card on file"),
("professional-services","Professional Services Payment Processing","invoices, retainers, ACH vs card"),
("law-firms","Law Firm Payment Processing","trust/IOLTA account considerations (consult bar rules), retainers"),
("accounting-firms","Accounting Firm Payment Processing","recurring engagements, invoices"),
("nonprofits","Nonprofit Donation Processing","donation pages, recurring gifts, fee coverage"),
("churches","Church & Ministry Giving Processing","text/online giving, recurring tithes"),
("schools-and-education","School & Education Payment Processing","tuition, plans, events"),
("daycare-centers","Daycare Payment Processing","weekly tuition autopay"),
("hotels-and-lodging","Hotel & Lodging Payment Processing","pre-auths, incidentals, PMS integration"),
("travel-agencies","Travel Agency Payment Processing","high chargeback risk, deposits"),
("event-venues","Event Venue Payment Processing","deposits, ticketing, on-site POS"),
("ticketing-and-events","Ticketing & Event Payment Processing","online tickets, door sales, peaks"),
("convenience-stores","Convenience Store Payment Processing","small tickets, EBT, speed"),
("grocery-stores","Grocery Store Payment Processing","EBT/SNAP, integrated lanes, volume pricing"),
("liquor-stores","Liquor Store Payment Processing","age verification, high volume, compliance"),
("gas-stations","Gas Station Payment Processing","pay-at-pump EMV, fleet cards, c-store"),
("pharmacies","Pharmacy Payment Processing","HSA/FSA IIAS, copays"),
("florists","Florist Payment Processing","phone orders, delivery, holidays"),
("pet-services","Pet Store & Grooming Payment Processing","appointments, retail"),
("photographers","Photography Business Payment Processing","deposits, invoices"),
("real-estate-and-property-management","Property Management Payment Processing","rent via ACH/card, recurring"),
("subscription-businesses","Subscription Business Payment Processing","recurring billing, dunning, churn"),
("b2b-wholesale","B2B & Wholesale Payment Processing","Level 2/3 data, invoices, ACH"),
("manufacturing","Manufacturing Payment Processing","large B2B, Level 3, net terms"),
("trucking-and-logistics","Trucking & Logistics Payment Processing","fleet cards, B2B, mobile"),
("towing-companies","Towing Company Payment Processing","roadside mobile payments"),
("home-services","Home Services Payment Processing","field service apps, invoices"),
("farmers-markets-and-vendors","Market Vendor Payment Processing","mobile, offline, low cost"),
("ecommerce-subscription-boxes","Subscription Box Payment Processing","recurring, card updater"),
("telehealth","Telehealth Payment Processing","card-not-present, recurring"),
("government-and-municipal","Government & Utility Payment Processing","convenience fees rules, online bill pay"),
]
SOL = [  # /solutions/<slug>/ — 30
("credit-card-processing","Credit Card Processing","merchant account basics, how authorization/settlement works"),
("zero-processing-fees","Zero Processing Fees Program","compliant dual pricing / cash discount explained, rules vary"),
("pos-systems","POS Systems","choosing POS, integrations, keep existing hardware"),
("credit-card-terminals","Credit Card Terminals","countertop, wireless, EMV/NFC, reprogramming"),
("mobile-payments","Mobile Payment Processing","readers, tap-to-phone, field use"),
("tap-to-pay","Tap to Pay & Contactless","NFC, Apple/Google Pay"),
("payment-gateway","Online Payment Gateway","CNP, tokenization, cart integrations"),
("virtual-terminal","Virtual Terminal","phone/mail orders, key-entry"),
("recurring-billing","Recurring Billing","subscriptions, memberships, autopay"),
("invoicing-and-payment-links","Invoicing & Payment Links","pay-by-link, faster AR"),
("ach-processing","ACH & eCheck Processing","bank payments, lower cost, timing"),
("level-2-and-level-3-processing","Level 2 & Level 3 Processing","B2B enhanced data, lower interchange"),
("next-day-funding","Next-Day Funding","settlement timing, cash flow"),
("pci-compliance","PCI Compliance","SAQs, scans, encryption"),
("fraud-prevention","Fraud Prevention","AVS/CVV, 3DS, velocity"),
("chargeback-management","Chargeback Management","disputes, representment"),
("high-risk-merchant-accounts","High-Risk Merchant Accounts","what makes high risk, realistic expectations"),
("ebt-processing","EBT Processing","SNAP acceptance basics"),
("gift-cards-and-loyalty","Gift Cards & Loyalty","programs, retention"),
("payment-analytics-dashboard","Payment Analytics & Reporting","dashboard insights"),
("emv-chip-processing","EMV Chip Card Processing","liability shift"),
("restaurant-pos","Restaurant POS","tables, KDS, tips"),
("retail-pos","Retail POS","inventory, SKUs"),
("ecommerce-integrations","E-commerce Platform Integrations","cart/plugin integrations"),
("merchant-cash-advance-referrals","Business Funding for Merchants","working capital options via partners like Fidelity Funding"),
("interchange-plus-pricing","Interchange-Plus Pricing","transparent pricing model"),
("surcharging-programs","Credit Card Surcharging","rules, caps, disclosures; vary by state/network"),
("free-statement-analysis","Free Merchant Statement Analysis","what we review"),
("switch-payment-processors","Switching Payment Processors","contracts, ETFs, smooth migration"),
("independent-sales-agent-program","Independent Sales Agent Program","residuals, ISO/ISA partnership"),
]
USE = [  # /use-cases/<slug>/ — 30
("lower-processing-fees","How to Lower Credit Card Processing Fees","levers"),
("accept-credit-cards-for-the-first-time","Accepting Credit Cards for the First Time","setup steps"),
("accept-payments-online","Accepting Payments Online","gateway, website"),
("accept-payments-by-phone","Taking Card Payments Over the Phone","virtual terminal, security"),
("accept-payments-on-the-go","Accepting Payments on the Go","mobile setups"),
("accept-payments-at-events","Accepting Payments at Events & Pop-Ups","offline, connectivity"),
("set-up-recurring-payments","Setting Up Recurring Payments","subscriptions"),
("get-paid-faster","Getting Paid Faster","next-day funding, invoices"),
("reduce-chargebacks","Reducing Chargebacks","prevention"),
("prevent-card-fraud","Preventing Card Fraud","CNP and in-person"),
("upgrade-to-emv-and-contactless","Upgrading to EMV & Contactless","hardware"),
("integrate-payments-with-pos","Integrating Payments With Your POS","integration choices"),
("offer-cash-discount","Offering a Cash Discount Program","implementation, signage"),
("pass-fees-to-customers","Passing Processing Fees to Customers","surcharge vs cash discount vs convenience fee"),
("process-b2b-payments","Processing B2B Payments","Level 2/3, ACH"),
("take-deposits-and-prepayments","Taking Deposits & Prepayments","pre-auth, card on file"),
("accept-tips","Accepting Tips on Card Payments","tip adjust, pooling"),
("handle-refunds-and-returns","Handling Refunds & Returns","policies"),
("multi-location-payments","Payments for Multi-Location Businesses","consolidated reporting"),
("open-a-new-business","Payments Setup for a New Business","checklist"),
("move-off-flat-rate-processing","Moving Off Flat-Rate Processing","when it pays"),
("cancel-processor-contract","Getting Out of a Processor Contract","ETF, leases"),
("terminal-lease-traps","Avoiding Terminal Lease Traps","non-cancellable leases"),
("become-pci-compliant","Becoming PCI Compliant","step by step"),
("accept-apple-pay-and-google-pay","Accepting Apple Pay & Google Pay","wallets"),
("accept-international-cards","Accepting International Cards","fees, currency"),
("sell-on-social-media","Selling on Social Media With Payment Links","links, DMs"),
("collect-overdue-invoices","Collecting Overdue Invoices With Payment Links","AR"),
("earn-residual-income","Earning Residual Income as a Payments Agent","agent economics"),
("audit-your-merchant-statement","Auditing Your Merchant Statement","line by line"),
]
BLOG = [  # /blog/<slug>/ — 90
("how-credit-card-processing-works","How Credit Card Processing Works, Step by Step","auth, clearing, settlement, parties"),
("interchange-explained","Interchange Fees Explained","who sets them, why they vary"),
("assessment-fees-explained","Card Network Assessment Fees Explained","network fees"),
("processor-markup-explained","Processor Markup: What You're Really Paying For","markup"),
("effective-rate-explained","Your Effective Rate: The Only Number That Matters","calculation"),
("tiered-pricing-explained","Tiered Pricing: Qualified vs. Non-Qualified","why it hides cost"),
("flat-rate-vs-interchange-plus","Flat-Rate vs. Interchange-Plus Pricing","comparison"),
("membership-and-subscription-pricing","Subscription (Membership) Pricing for Processing","model"),
("dual-pricing-explained","Dual Pricing Explained","how it works, rules"),
("cash-discount-vs-surcharge","Cash Discount vs. Surcharge: What's the Difference?","compliance overview"),
("surcharge-rules-by-state","Credit Card Surcharge Rules: What to Check in Your State","no specifics claimed as current law; varies"),
("convenience-fees-explained","Convenience Fees Explained","card network rules"),
("debit-vs-credit-processing-costs","Debit vs. Credit: Why Costs Differ","regulated debit, rewards cards"),
("rewards-cards-cost-more","Why Rewards Cards Cost Merchants More","interchange categories"),
("card-present-vs-card-not-present","Card-Present vs. Card-Not-Present Transactions","risk and cost"),
("what-is-a-merchant-account","What Is a Merchant Account?","basics"),
("payment-facilitator-vs-merchant-account","Payment Facilitator vs. Dedicated Merchant Account","trade-offs"),
("what-is-an-iso","What Is an ISO in Payments?","roles"),
("what-is-a-payment-gateway","What Is a Payment Gateway?","basics"),
("payment-processor-vs-gateway","Payment Processor vs. Payment Gateway","difference"),
("how-to-read-a-merchant-statement","How to Read a Merchant Statement","sections"),
("hidden-fees-on-merchant-statements","12 Hidden Fees on Merchant Statements","list"),
("pci-non-compliance-fee","The PCI Non-Compliance Fee and How to Stop Paying It","SAQ"),
("early-termination-fees","Processor Early Termination Fees","contracts"),
("terminal-leasing-vs-buying","Leasing vs. Buying a Card Terminal","total cost"),
("best-pos-features-small-business","POS Features That Matter for Small Businesses","checklist"),
("emv-liability-shift","The EMV Liability Shift Explained","counterfeit fraud"),
("contactless-payments-guide","Contactless Payments: A Merchant Guide","NFC"),
("mobile-wallets-explained","Apple Pay, Google Pay & Mobile Wallets Explained","tokenization"),
("tokenization-explained","Payment Tokenization Explained","security"),
("encryption-p2pe-explained","Point-to-Point Encryption (P2PE) Explained","security"),
("3d-secure-explained","3-D Secure Explained","CNP auth"),
("avs-and-cvv","AVS and CVV Checks: Your First Fraud Defense","basics"),
("chargeback-reason-codes","Chargeback Reason Codes Explained","common categories"),
("how-to-win-a-chargeback","How to Win a Chargeback Dispute","representment"),
("friendly-fraud","Friendly Fraud: What It Is and How to Fight It","prevention"),
("card-testing-attacks","Card Testing Attacks on Online Stores","prevention"),
("refund-vs-chargeback","Refund vs. Chargeback","why refunding early helps"),
("next-day-funding-explained","Next-Day Funding: How Settlement Timing Works","batches, cutoffs"),
("batch-settlement-explained","Batch Settlement Explained","closing batches"),
("ach-vs-credit-card","ACH vs. Credit Card Payments for Businesses","cost/timing"),
("recurring-billing-best-practices","Recurring Billing Best Practices","dunning, updater"),
("account-updater","Card Account Updater: Fewer Failed Payments","how it works"),
("level-2-3-data-explained","Level 2 and Level 3 Data Explained","fields, savings"),
("b2b-payment-trends","Accepting Cards From Business Customers","corporate/purchasing cards"),
("ebt-snap-acceptance","Accepting EBT/SNAP: A Retailer Guide","basics"),
("hsa-fsa-card-acceptance","Accepting HSA and FSA Cards","IIAS basics"),
("tipping-on-card-terminals","Tipping on Card Terminals: Setup & Etiquette","options"),
("restaurant-payment-tips","Restaurant Payment Tips to Cut Costs","practical"),
("retail-payment-tips","Retail Payment Tips to Cut Costs","practical"),
("ecommerce-checkout-optimization","Checkout Optimization for Online Stores","conversion"),
("high-risk-industries-explained","Why Some Industries Are 'High Risk' for Processing","factors"),
("merchant-account-approval","How Merchant Account Approval Works","underwriting"),
("merchant-account-holds-and-reserves","Merchant Account Holds and Reserves","why they happen"),
("matched-list-explained","The MATCH List Explained","termination file"),
("switching-processors-checklist","Switching Processors: A Checklist","steps"),
("questions-to-ask-a-processor","15 Questions to Ask a Payment Processor","list"),
("processor-contract-red-flags","Red Flags in Payment Processing Contracts","auto-renew, ETF, leases"),
("negotiate-processing-rates","How to Negotiate Lower Processing Rates","levers"),
("small-ticket-transactions","Small-Ticket Transactions and Processing Costs","per-transaction fees"),
("large-ticket-transactions","Large-Ticket Transactions: Limits and Risk","limits"),
("international-cards-fees","Cross-Border and International Card Fees","fees"),
("cash-vs-card-small-business","Cash vs. Card for Small Businesses","handling costs"),
("going-cashless","Should Your Business Go Cashless?","considerations, local laws vary"),
("payment-links-guide","Payment Links: A Small Business Guide","use cases"),
("qr-code-payments","QR Code Payments for Small Businesses","use"),
("buy-now-pay-later-for-merchants","Buy Now, Pay Later for Merchants","pros/cons"),
("omnichannel-payments","Omnichannel Payments: One Account, Every Channel","unified"),
("payment-data-analytics","Using Payment Data to Grow Sales","insights"),
("customer-loyalty-with-payments","Building Loyalty Through Your Payment System","programs"),
("gift-card-programs","Running a Gift Card Program","setup"),
("holiday-season-payments-prep","Preparing Your Payments for the Holiday Rush","checklist"),
("seasonal-business-payments","Payments for Seasonal Businesses","pausing, fees"),
("payment-security-checklist","Payment Security Checklist for Small Businesses","list"),
("data-breach-response","What to Do After a Payment Data Breach","steps (consult counsel)"),
("employee-theft-pos","Preventing Employee Theft at the POS","controls"),
("offline-payments","Taking Payments When the Internet Goes Down","offline mode"),
("payment-terminal-troubleshooting","Card Terminal Troubleshooting Guide","common fixes"),
("receipt-best-practices","Receipt Best Practices: Paper, Email and SMS","options"),
("payments-for-startups","Payment Processing for Startups","first setup"),
("independent-sales-agent-guide","How to Become a Merchant Services Sales Agent","path"),
("residual-income-explained","Merchant Services Residuals Explained","how agents earn"),
("iso-vs-agent","ISO vs. Independent Sales Agent","roles"),
("selling-merchant-services","How to Sell Merchant Services: A Beginner's Guide","prospecting"),
("statement-analysis-sales-tool","Using Statement Analysis to Win Merchants","agent tactic"),
("future-of-payments","The Future of Payments for Small Businesses","trends without stats"),
("payments-glossary-guide","Payment Processing Terms Every Owner Should Know","narrative glossary"),
("processing-fees-tax-deductible","Are Credit Card Processing Fees Tax Deductible?","general, consult CPA"),
("checks-vs-cards","Paper Checks vs. Card Payments for Small Businesses","cost, speed, risk"),
("working-capital-for-merchants","Working Capital Options for Card-Accepting Businesses","funding via partners, Fidelity Funding mention"),
]
PAGES = [("industries", *x) for x in IND] + [("solutions", *x) for x in SOL] + [("use-cases", *x) for x in USE] + [("blog", *x) for x in BLOG]
if __name__ == "__main__":
    import json, collections
    print(len(PAGES), collections.Counter(p[0] for p in PAGES))
    assert len({p[1] for p in PAGES}) == len(PAGES), [s for s, n in collections.Counter(p[1] for p in PAGES).items() if n > 1]
    json.dump([{"category": c, "slug": s, "title": t, "angle": a, "url": f"/{c}/{s}/"} for c, s, t, a in PAGES], open("content/manifest.json", "w"), indent=0)
